<?php

declare(strict_types=1);

return [
    'dry_run' => env('GLPI_AI_DRY_RUN', true),
    'auto_assign' => env('GLPI_AI_AUTO_ASSIGN', false),
    'confidence_threshold_technician' => (int) env('GLPI_AI_CONFIDENCE_TECHNICIAN', 60),
    'confidence_threshold_group' => (int) env('GLPI_AI_CONFIDENCE_GROUP', 45),
    'max_similar_tickets' => (int) env('GLPI_AI_MAX_SIMILAR_TICKETS', 10),
    'minimum_similar_tickets' => (int) env('GLPI_AI_MINIMUM_SIMILAR_TICKETS', 3),
    'minimum_gap_between_candidates' => (float) env('GLPI_AI_MINIMUM_GAP_BETWEEN_CANDIDATES', 3),
    'minimum_context_score_for_technician' => (float) env('GLPI_AI_MINIMUM_CONTEXT_SCORE_FOR_TECHNICIAN', 0.35),
    'allow_group_recommendation' => env('GLPI_AI_ALLOW_GROUP_RECOMMENDATION', false),
    'ranking_weights' => [
        'text_similarity' => 0.40,
        'category' => 0.20,
        'history' => 0.25,
        'recency' => 0.10,
        'workload' => 0.05,
    ],
    'sensitive_words' => [
        'senha', 'permissao', 'permissão', 'admin', 'administrador', 'root',
        'banco de dados', 'LGPD', 'dados pessoais', 'incidente critico', 'incidente crítico',
        'seguranca', 'segurança', 'vazamento', 'invasao', 'invasão', 'phishing', 'malware', 'ransomware',
    ],
    'blocked_categories' => [],
    'blocked_technicians' => [],
    'new_ticket_statuses' => array_map('intval', explode(',', env('GLPI_AI_NEW_TICKET_STATUSES', '1'))),
    'historical_ticket_statuses' => array_map('intval', explode(',', env('GLPI_AI_HISTORICAL_TICKET_STATUSES', '5,6'))),
    'only_unassigned_new_tickets' => env('GLPI_AI_ONLY_UNASSIGNED_NEW_TICKETS', false),
    'ignore_group_assignment_for_new_tickets' => env('GLPI_AI_IGNORE_GROUP_ASSIGNMENT_FOR_NEW_TICKETS', true),
    'hydrate_ticket_solutions' => env('GLPI_AI_HYDRATE_TICKET_SOLUTIONS', true),
    'hydrate_ticket_followups' => env('GLPI_AI_HYDRATE_TICKET_FOLLOWUPS', false),
    'embedding_provider' => env('GLPI_AI_EMBEDDING_PROVIDER', 'openrouter'),
    'embedding_model' => env('GLPI_AI_EMBEDDING_MODEL'),
    'embedding_dimension' => (int) env('GLPI_AI_EMBEDDING_DIMENSION', 1536),
    'openrouter_model' => env('OPENROUTER_MODEL'),
    'algorithm_version' => env('GLPI_AI_ALGORITHM_VERSION', 'mvp-1.0.0'),
    'text_limit' => (int) env('GLPI_AI_TEXT_LIMIT', 12000),
    'request_timeout' => (int) env('GLPI_AI_REQUEST_TIMEOUT', 30),
    'queue_name' => env('GLPI_AI_QUEUE_NAME', 'glpi-ai'),
    'enable_manual_approval' => env('GLPI_AI_ENABLE_MANUAL_APPROVAL', true),
    'require_human_approval' => env('GLPI_AI_REQUIRE_HUMAN_APPROVAL', true),
    'enable_dashboard_settings_edit' => env('GLPI_AI_ENABLE_DASHBOARD_SETTINGS_EDIT', false),
    'openrouter' => [
        'base_url' => env('OPENROUTER_BASE_URL', 'https://openrouter.ai/api/v1'),
        'api_key' => env('OPENROUTER_API_KEY'),
        'site_url' => env('OPENROUTER_SITE_URL'),
        'app_name' => env('OPENROUTER_APP_NAME', 'GLPI BOT'),
        'verify_ssl' => env('OPENROUTER_VERIFY_SSL', true),
    ],
    'glpi_api' => [
        'base_url' => env('GLPI_API_BASE_URL'),
        'web_base_url' => env('GLPI_WEB_BASE_URL', 'https://chamados.corensc.gov.br'),
        'app_token' => env('GLPI_APP_TOKEN'),
        'user_token' => env('GLPI_USER_TOKEN'),
        'verify_ssl' => env('GLPI_API_VERIFY_SSL', true),
        'entity_id' => env('GLPI_API_ENTITY_ID', 'all'),
        'entity_recursive' => env('GLPI_API_ENTITY_RECURSIVE', true),
    ],
];
